spring.jpa:
spring:
  jpa:
    database: postgresql
    hibernate.dialect: org.hibernate.dilect.PostgreSQLDialect
    hibernate.ddl-auto: update
    properties.hibernate.format_sql: true
    show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-44-205-112-253.compute-1.amazonaws.com/d4ldc2npgseuen
  username: cnibqjsyysmzdj
  password: 315dd38a5d8b729e71643d604608fd933b6a8e800b08c9dfb44ed5428e229574
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: sjk.sns-application-2022.secret_key
  # 30 days
  token.expired-time-ms: 2592000000